# Generated by Django 4.2.18 on 2025-02-27 15:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkedAccount",
            fields=[
                ("partner_tracking_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("account_tracking_id", models.UUIDField()),
                ("phone_number", models.CharField(max_length=15)),
                ("merchant_id", models.CharField(max_length=255)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Linked Account",
                "verbose_name_plural": "Linked Accounts",
            },
        ),
        migrations.CreateModel(
            name="PartnerTransaction",
            fields=[
                (
                    "operation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("P2P", "P2P"),
                            ("PAYMENT", "PAYMENT"),
                            ("GIFTCARD", "GIFTCARD"),
                            ("TOPUP", "TOPUP"),
                            ("BILL_PAYMENT", "BILL_PAYMENT"),
                            ("DEVELOPER_API", "DEVELOPER_API"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("amount_in_millimes", models.IntegerField()),
                ("operation_payload", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "operation_status",
                    models.CharField(
                        choices=[
                            ("A", "Approved"),
                            ("D", "Declined"),
                            ("P", "Pending"),
                            ("E", "Expired"),
                            ("DP", "DATA_API_PENDING"),
                            ("DC", "DATA_API_CONFIRMED"),
                            ("DF", "DATA_API_FAILED"),
                            ("SP", "SERVICE_PENDING"),
                            ("SF", "SERVICE_FAILED"),
                            ("SC", "SERVICE_CONFIRMED"),
                            ("RP", "REFUND_PENDING"),
                            ("RF", "REFUND_FAILED"),
                            ("RC", "REFUND_CONFIRMED"),
                            ("WP", "WORKER_PENDING"),
                        ],
                        default="P",
                        max_length=20,
                    ),
                ),
                ("blockchain_ref", models.CharField(blank=True, max_length=255, null=True)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("time_modified", models.DateTimeField(auto_now=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiver_transactions",
                        to="partners.linkedaccount",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sender_transactions",
                        to="partners.linkedaccount",
                    ),
                ),
            ],
        ),
    ]
