# Generated by Django 3.2.25 on 2025-03-05 10:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkedaccount",
            name="partner_tracking_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
