# Generated by Django 4.2.18 on 2025-02-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linkedaccount",
            name="id",
        ),
        migrations.AlterField(
            model_name="linkedaccount",
            name="account_tracking_id",
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name="linkedaccount",
            name="partner_tracking_id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
