# Generated by Django 4.2.20 on 2025-04-26 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_flouciapp_tracking_id"),
        ("partners", "0002_alter_linkedaccount_partner_tracking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedaccount",
            name="app",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="api.flouciapp"
            ),
        ),
        migrations.AddField(
            model_name="linkedaccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
