# Generated by Django 4.2.18 on 2025-02-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0002_remove_linkedaccount_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedaccount",
            name="phone_number",
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
    ]
