# Generated by Django 4.2.17 on 2025-04-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_alter_linkedaccount_partner_tracking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedaccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="linkedaccount",
            name="public_token",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
