# Generated by Django 4.2.17 on 2025-03-02 22:27

from django.db import migrations, models


def populate_id_field(apps, schema_editor):
    PartnerTransaction = apps.get_model("partners", "PartnerTransaction")
    for transaction in PartnerTransaction.objects.all():
        if transaction.id is None:
            transaction.id = transaction.pk  # Assign the primary key directly
            transaction.save(update_fields=["id"])  # Save only the 'id' field


class Migration(migrations.Migration):
    dependencies = [
        ("partners", "0003_linkedaccount_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnertransaction",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False, null=True),
        ),
        migrations.RunPython(populate_id_field),
        migrations.AlterField(
            model_name="partnertransaction",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
