# Generated by Django 4.2.11 on 2025-01-16 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("public_token", models.CharField(max_length=60, unique=True)),
                ("wallet", models.CharField(max_length=35)),
                ("status", models.CharField(max_length=20)),
                ("active", models.BooleanField()),
                ("date_created", models.DateTimeField()),
                ("webhook", models.CharField(blank=True, max_length=255, null=True)),
                ("sms_key", models.CharField(blank=True, max_length=6, null=True)),
                ("test", models.BooleanField()),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("private_token", models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ("image_url", models.CharField(blank=True, max_length=1000, null=True)),
                ("deleted", models.BooleanField()),
                ("gross", models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ("transaction_number", models.BigIntegerField(blank=True, null=True)),
                ("revoke_number", models.IntegerField(blank=True, null=True)),
                ("last_revoke_date", models.DateField(blank=True, null=True)),
                ("app_id", models.UUIDField(blank=True, null=True)),
                ("merchant_id", models.BigIntegerField()),
            ],
            options={
                "db_table": "app",
            },
        ),
        migrations.CreateModel(
            name="JhiAuthority",
            fields=[
                ("name", models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "jhi_authority",
            },
        ),
        migrations.CreateModel(
            name="JhiUser",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=50, unique=True)),
                ("password_hash", models.CharField(max_length=60)),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=191, null=True, unique=True)),
                ("image_url", models.CharField(blank=True, max_length=1000, null=True)),
                ("activated", models.BooleanField()),
                ("lang_key", models.CharField(blank=True, max_length=10, null=True)),
                ("activation_key", models.CharField(blank=True, max_length=20, null=True)),
                ("reset_key", models.CharField(blank=True, max_length=20, null=True)),
                ("created_by", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("reset_date", models.DateTimeField(blank=True, null=True)),
                ("last_modified_by", models.CharField(blank=True, max_length=50, null=True)),
                ("last_modified_date", models.DateTimeField(blank=True, null=True)),
                ("tmp_email", models.CharField(blank=True, max_length=191, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=12, null=True)),
                ("sms_key", models.CharField(blank=True, max_length=6, null=True)),
                ("email_validated", models.BooleanField()),
                ("deleted", models.BooleanField()),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "jhi_user",
            },
        ),
        migrations.CreateModel(
            name="MetricsLastUpdate",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("last_update_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "metrics_last_update",
            },
        ),
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day", models.DateField(blank=True, null=True)),
                ("transactions", models.BigIntegerField(blank=True, null=True)),
                ("daily_metrics_id", models.UUIDField(blank=True, null=True)),
                ("amount_sum", models.BigIntegerField(blank=True, null=True)),
                ("fee_sum", models.BigIntegerField(blank=True, null=True)),
                ("amount_average", models.FloatField(blank=True, null=True)),
                ("fee_average", models.FloatField(blank=True, null=True)),
                ("transaction_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "app",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to="api.app"
                    ),
                ),
            ],
            options={
                "db_table": "daily_metrics",
            },
        ),
        migrations.AddField(
            model_name="app",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="api.jhiuser"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="app",
            unique_together={("user", "name")},
        ),
        migrations.CreateModel(
            name="JhiUserAuthority",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="api.jhiuser",
                    ),
                ),
                (
                    "authority_name",
                    models.ForeignKey(
                        db_column="authority_name",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.jhiauthority",
                    ),
                ),
            ],
            options={
                "db_table": "jhi_user_authority",
                "unique_together": {("user", "authority_name")},
            },
        ),
    ]
