# Generated by Django 4.2.18 on 2025-02-28 10:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JhiUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=50, unique=True)),
                ("password_hash", models.CharField(editable=False, max_length=60)),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(blank=True, max_length=191, null=True)),
                ("image_url", models.CharField(blank=True, max_length=1000, null=True)),
                ("activated", models.BooleanField(default=True)),
                ("lang_key", models.CharField(blank=True, max_length=10, null=True)),
                ("activation_key", models.CharField(blank=True, max_length=20, null=True)),
                ("reset_key", models.CharField(blank=True, max_length=20, null=True)),
                ("created_by", models.CharField(default="system", max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("reset_date", models.DateTimeField(blank=True, null=True)),
                ("last_modified_by", models.CharField(default="system", max_length=50)),
                ("last_modified_date", models.DateTimeField(auto_now=True, null=True)),
                ("tmp_email", models.CharField(blank=True, max_length=191, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=12, null=True)),
                ("sms_key", models.CharField(blank=True, max_length=6, null=True)),
                ("email_validated", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                ("user_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "jhi_user",
            },
        ),
        migrations.CreateModel(
            name="Peer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("tracking_id", models.UUIDField(blank=True, null=True)),
                ("activated", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_modified_date", models.DateTimeField(auto_now=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=12, null=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("Individual", "Individual"), ("Merchant", "Merchant")],
                        default="Merchant",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "peer",
            },
        ),
        migrations.CreateModel(
            name="FlouciApp",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("app_id", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("public_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("private_token", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("wallet", models.CharField(max_length=35)),
                (
                    "status",
                    models.CharField(
                        choices=[("VERIFIED", "Verified"), ("UNVERIFIED", "Unverified")],
                        default="VERIFIED",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("webhook", models.URLField(blank=True, max_length=1000, null=True)),
                ("test", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("gross", models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ("transaction_number", models.BigIntegerField(blank=True, null=True)),
                ("revoke_number", models.IntegerField(blank=True, null=True)),
                ("last_revoke_date", models.DateField(blank=True, null=True)),
                ("merchant_id", models.BigIntegerField(blank=True, null=True)),
                ("has_partner_access", models.BooleanField(default=False)),
                ("has_advanced_payments_access", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="api.peer"
                    ),
                ),
            ],
            options={
                "db_table": "flouciapp",
            },
        ),
        migrations.CreateModel(
            name="App",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("public_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("wallet", models.CharField(max_length=35)),
                (
                    "status",
                    models.CharField(
                        choices=[("VERIFIED", "Verified"), ("UNVERIFIED", "Unverified")],
                        default="VERIFIED",
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField()),
                ("webhook", models.CharField(blank=True, max_length=255, null=True)),
                ("sms_key", models.CharField(blank=True, max_length=6, null=True)),
                ("test", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("private_token", models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ("image_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("gross", models.DecimalField(blank=True, decimal_places=0, max_digits=38, null=True)),
                ("transaction_number", models.BigIntegerField(blank=True, null=True)),
                ("revoke_number", models.IntegerField(blank=True, null=True)),
                ("last_revoke_date", models.DateField(blank=True, null=True)),
                ("app_id", models.UUIDField(blank=True, null=True)),
                ("merchant_id", models.BigIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="api.jhiuser"
                    ),
                ),
            ],
            options={
                "db_table": "app",
            },
        ),
    ]
