# Generated by Django 4.2.11 on 2025-01-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jhiuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
