# Generated by Django 4.2.18 on 2025-02-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flouciapp",
            name="has_advanced_payments_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="flouciapp",
            name="has_partner_access",
            field=models.BooleanField(default=False),
        ),
    ]
