# Generated by Django 4.2.18 on 2025-02-17 15:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="peer",
            table="peer",
        ),
    ]
