# Generated by Django 3.2.25 on 2025-03-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="revoke_number",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
