# Generated by Django 3.2.25 on 2025-03-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_app_revoke_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flouciapp",
            name="user",
        ),
        migrations.AddField(
            model_name="flouciapp",
            name="tracking_id",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name="Peer",
        ),
    ]
