# Generated by Django 3.2.25 on 2025-04-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20250318_1448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flouciapp",
            name="revoke_number",
            field=models.IntegerField(default=0),
        ),
    ]
