# Generated by Django 4.2.18 on 2025-04-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_flouciapp_revoke_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flouciapp",
            name="tracking_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
