from rest_framework.permissions import BasePermission

from utils.jwt_helpers import verify_token


class IsJWTAuthenticated(BasePermission):
    """
    has a valid jwt generated by backend
    """

    def has_permission(self, request, view):
        token = request.META.get("HTTP_AUTHORIZATION")
        verified, data = verify_token(token)
        if not verified:
            return False
        for key, value in data.items():
            setattr(request, key, value)
        return True
